import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const Background = dynamic(() => import("./background"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
    <html lang="en">
      <div
        style={{
          position: "fixed",
          zIndex: "1",
          width: "100%",
          height: "100%",
        }}
      >
        <Background />
        <main
          style={{
            position: "fixed",
            zIndex: "2",
          }}
        >
          {children}
        </main>
      </div>
    </html>
  );
}
